### ISSUE TITLE
Crash when using (right-click) any items with Harvest Scythes installed

### ISSUE THREAD

**Issue by LiLi-Stormstout** [LordDeatHunter/HarvestScythes#1]
My Minecraft crashes at random when I attempt to use any items with the **Harvest Scythes** mod installed, the issue _does not_ occur at all if I remove **Harvest Scythes** from my modpack:

[crash-2020-12-30_21.27.59-client.txt](https://github.com/LordDeatHunter/HarvestScythes/files/5756681/crash-2020-12-30_21.27.59-client.txt)

**Comment by LiLi-Stormstout** [comment]
Taking this opportunity to also suggest / request adding compatibility for Tech Reborn's tool materials in a future version, no biggie though, AstroMine support is greatly appreciated. :)

**Comment by LordDeatHunter** [comment]
Done and done 👍

**Comment by LiLi-Stormstout** [comment]
> Done and done 👍

Thank you, you rock! :)

Unfortunately, the Peridot Scythe shows up as a purple-black checkerboard in game, but it appears to stem from **Peridot_Scythe.json** being missing.

Writing it and adding it into the mod's **.jar** fixed the issue in-game for me, I have appended the **.json** down below:

[peridot_scythe.zip](https://github.com/LordDeatHunter/HarvestScythes/files/5757149/peridot_scythe.zip)
