### ISSUE TITLE
Harvest scythes probably needs another update

### ISSUE THREAD

**Issue by Sunconure11** [LordDeatHunter/HarvestScythes#10]
https://pastebin.com/bCk6yUcx

**Comment by Sunconure11** [comment]
There's also possible compat issues with Charm.

https://github.com/svenhjol/Charm/issues/535

**Comment by Sunconure11** [comment]
I can confirm it's charm at this point.

**Comment by Sunconure11** [comment]
https://pastebin.com/qb7BGEtg

Okay, I'm an idiot. The issue a cross-compat one between this and BN.

**Comment by LordDeatHunter** [comment]
Is this in a dev environment? I am experiencing no issues with the latest HarvestScythes, BetterNether and Charm together.

**Comment by Sunconure11** [comment]
Not a dev environment, no.

**Comment by Sunconure11** [comment]
Any news on this? I'm still encountering it on 2.0.0.

**Comment by Sunconure11** [comment]
https://pastebin.com/9zBYwSAV

**Comment by Sunconure11** [comment]
https://pastebin.com/Laf0us0F

With all mods (but a few junky ones removed) active, this is my log.

**Comment by LordDeatHunter** [comment]
Can you join my discord and help me debug? https://discord.gg/vMjzgS4

**Comment by LordDeatHunter** [comment]
Should be fixed as of 2.0.1
