### ISSUE TITLE
HarvestScythes conflicts with BetterNether, causes crash on startup of server.

### ISSUE THREAD

**Issue by ArtiTice** [LordDeatHunter/HarvestScythes#13]
On startup of fabric modded server, it seems to abort launch/crash when these two mods are installed together. This only happens when running the server. Doesn't happen when running the Minecraft client. 

Here's the log.
[latest.log](https://github.com/LordDeatHunter/HarvestScythes/files/6450191/latest.log)

I saw the other issues posted that had issues with BetterNether and Harvest Scythe, and I am using the latest versions for both mods.

**Comment by LordDeatHunter** [comment]
It should be re-fixed now. This bug will haunt me forever,
