### ISSUE TITLE
I don't even use HarvestScythes but i have an issue with it?

### ISSUE THREAD

**Issue by Blunder-G** [LordDeatHunter/HarvestScythes#14]
In MultiMC, i saw this error and it's red colored error (important). Strange thing is i don't use this mod...

Error:

[19:40:05] [main/WARN]: Error loading class: wraith/harvest_scythes/ScytheTool (java.lang.ClassNotFoundException: wraith/harvest_scythes/ScytheTool)

**Comment by LordDeatHunter** [comment]
It seems some mod is trying to access the scythes without checking if the mod is installed first.
Can you post the full log as well as your mod list?

**Comment by Blunder-G** [comment]
Mod list: 
[crash-2021-06-11_00.11.02-client.txt](https://github.com/LordDeatHunter/HarvestScythes/files/6634428/crash-2021-06-11_00.11.02-client.txt)

Log: 
[latest.log](https://github.com/LordDeatHunter/HarvestScythes/files/6634429/latest.log)

**Comment by LordDeatHunter** [comment]
Can you send the crash-server as well? I'm seeing errors from all sorts of mods here.

**Comment by LordDeatHunter** [comment]
Out of those mods, the only one I'm aware that messes with Harvest Scythtes is RPGStats, but I'm pretty sure it checks if the mod is installed first.

**Comment by Blunder-G** [comment]
crash server? whaaaa...

**Comment by Blunder-G** [comment]
and yeah i have a lot of error but i don't know which one is which one...

**Comment by LordDeatHunter** [comment]
In your crashes folder, there should be crash-client.txt and crash-server.txt

**Comment by P03W** [comment]
> Out of those mods, the only one I'm aware that messes with Harvest Scythtes is RPGStats, but I'm pretty sure it checks if the mod is installed first.

Seems to be a minor issue with the [@Pseudo](https://jenkins.liteloader.com/job/Mixin/javadoc/org/spongepowered/asm/mixin/Pseudo.html) annotation, its harmless but I don't see a way to suppress it

I switched to using Pseudo over a mixin plugin because its less files to manage and update
If this becomes an issue id be happy to switch back

**Comment by LordDeatHunter** [comment]
Should I close the issue?

**Comment by P03W** [comment]
Yeah, ive opened an issue on RPGStats about possibly suppressing this
