### ISSUE TITLE
[1.16.5] Missing Univite Machete Texture (Fix Attached)

### ISSUE THREAD

**Issue by Li-Liu** [LordDeatHunter/HarvestScythes#15]
### Issue Description:

The texture for the Univite Machete, made with _Astromine's_ Univite Ingots, is missing, and the tool in-game displays as the checkerboard _missing texture_.

Including a texture and mcmeta file into the correct places inside of the jar gets rid of the issue entirely. (See **Additional Note(s)** below.

### Step(s) to Reproduce:

**1.-** Install Harvest Scythes
**2.-** Install Astromine
**3.-** Enter a World
**4.-** Check REI or craft the Univite Machete.

### Environment:

- Java 16.0.1 OpenJ9 (AdoptOpenJDK)
- Fabric 0.11.6
- Harvest Scythes 2.0.4
- Astromine 1.11.5

### Log(s):

N/A

### Screenshot(s):

N/A

### Additional Note(s):

I have bundled a self-made texture for the Univite Machete that I am currently using in my Minecraft Modpack to circumvent this issue, I have attached it to this issue in case that you might find it to be useful or helpful.

[Univite Machete (png & mcmeta files).zip](https://github.com/LordDeatHunter/HarvestScythes/files/6815507/Univite.Machete.png.mcmeta.files.zip)

**Comment by LordDeatHunter** [comment]
I appreciate the fix, but I won't be adding this, as Astromine is discontinued.
