### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'harvest_scythes'! Exit Code: -1

### ISSUE THREAD

**Issue by KidlatSV** [LordDeatHunter/HarvestScythes#2]
I don't really know if harvest scythes is causing the crash, or something else.

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 1/1/21 3:45 AM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'harvest_scythes'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: java.lang.NoSuchFieldError: TANTALITE
	at wraith.harvest_scythes.support.MythicMetalsSupport.loadItems(MythicMetalsSupport.java:48)
	at wraith.harvest_scythes.HarvestScythes.onInitialize(HarvestScythes.java:31)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2548/2103311527.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1194013608 bytes (1138 MB) / 2986344448 bytes (2848 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 6
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 1.12.2+1.16.4
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		advancements-enlarger: Advancements Enlarger 0.2.3
		advdebug: Advancements Debug 2.2.0
		adventurez: AdventureZ 1.1.5
		amecsapi: Amecs API 1.1.1+mc1.16-rc1
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		architectury: Architectury 1.2.65
		arstheurgia: Ars Theurgia 1.0.5
		artifacts: Artifacts 2.0.2+1.16.4-fabric
		artifice: Artifice 0.13.1+1.16.2-rc1
		artofalchemy: Art of Alchemy: Memoriam 1.0.0-rc4+1.16.4
		astromine: Astromine 1.11.4+fabric-1.16.3
		astromine-core: Astromine: Core 1.11.4+fabric-1.16.3
		astromine-discoveries: Astromine: Discoveries 1.11.4+fabric-1.16.3
		astromine-foundations: Astromine: Foundations 1.11.4+fabric-1.16.3
		astromine-technologies: Astromine: Technologies 1.11.4+fabric-1.16.3
		astromine-transportations: Astromine: Transportations 1.11.4+fabric-1.16.3
		atbyw: All The Blocks You Want (ATBYW) 1.3.4
		autoconfig1u: Auto Config v1 Updated 3.3.1
		backslot: BackSlot 1.1.8
		bambootweaks: Bamboo Tweaks unspecified
		battletowers: Battle Towers 3.3.1-beta-1.16.4
		bebooks: Better Enchanted Books 1.1.4
		bedspreads: Bedspreads 1.3.1-1.16.4
		bettercaves: YUNG's Better Caves 1.16.2-1.0.3
		betterend: Better End 0.8.4-beta
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
		betternether: Better Nether 5.0.4
		biomemakeover: Biome Makeover 1.16.4-1.1.6
		blade: Blade 2.0.0
		blast: BLAST 1.5
		blockus: Blockus 2.0.1+1.16.4
		blue_endless_jankson: jankson +
		borderlessmining: Borderless Mining 1.0.6+1.16.2
		byg: BYG 1.1.3
		cameraoverhaul: Camera Overhaul 1.0.1-fabric-1.16
		campanion: Campanion 1.3.1+build.51
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.0.2
		cardinal-components: Cardinal Components API 2.7.10
		cardinal-components-base: Cardinal Components API (base) 2.7.10
		cardinal-components-block: Cardinal Components API (blocks) 2.7.10
		cardinal-components-chunk: Cardinal Components API (chunks) 2.7.10
		cardinal-components-entity: Cardinal Components API (entities) 2.7.10
		cardinal-components-item: Cardinal Components API (items) 2.7.10
		cardinal-components-level: Cardinal Components API (world saves) 2.7.10
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.7.10
		cardinal-components-util: Cardinal Components API (utilities) 2.7.10
		cardinal-components-world: Cardinal Components API (worlds) 2.7.10
		carrier: Carrier 1.6.1
		cavebiomes: Cave Biomes 0.5.1
		ce_foodstuffs: Common Expansion: Foodstuffs 1.1.2
		chainmail: Chainmail 0.5.0
		charm: Charm 2.2.1
		charmonium: Charmonium 2.2.0
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cinderscapes: Cinderscapes 1.3.0+build.51
		cleancut: CleanCut mc1.16-2.1-fabric
		cloth-armor-api-v1: Cloth Armor API v1 1.4.8
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.9
		cloth-common-events-v1: Cloth Common Events v1 1.4.8
		cloth-config2: Cloth Config v4 4.8.3
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.8
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.8
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.8
		colorfulcolumns: Colorful Columns 1.0.0
		columns: Columns 1.1.1
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compressedblocks: Compressed Blocks 1.0
		controlling: Controlling For Fabric 1.1.2
		couplings: Couplings 1.3.3
		crowdin-translate: CrowdinTranslate 1.2
		crumbs: Crumbs 1.0.6
		cspirit: Christmas Spirit 1.0.0+mc.1.16.4
		curios: Curios API 0.0.10-1.16.3
		customportalapi: customportalapi 0.0.1-beta18-1.16
		darkpaintings: Dark Paintings 2.0.0
		dawn: Dawn API 1.6.1
		desolation: Desolation 1.0.3
		diggusmaximus: Diggus Maximus 1.4.2-1.16.3
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.2
		discontinuous_beacon_beams: Discontinuous Beacon Beams 1.0+MC1.16.2-1.16.4
		dyetherite: Dyetherite 1.0.0+1.16.4
		dynamicfps: Dynamic FPS 1.1.4
		eggtab: Egg Tab 1.3.2+1.16-fabric
		enchantment_lore: EnchantmentLore 1.1+MC1.16.1-1.16.4
		enderitemod: Enderite Mod 1.2.2
		expandedstorage: ExpandedStorage 5.6.31
		ezpas: Ezpas 1.2.3-1.16.2
		fabric: Fabric API 0.29.0+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.1+cbe9176f3a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-diagonal-panes: Fabric Diagonal Panes 0.4.0
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.0+79b23bee3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-furnaces: Fabric Furnaces 1.3.2-1.16.2
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.5+cbe9176f3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.2+cbe9176f3a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
		fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-models-v0: Fabric Models (v0) 0.2.0+cbe9176f3a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: Fabric Particles (v1) 0.2.3+cbe9176f3a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.0+cbe9176f3a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db23a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.0+c26373133a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.0+552549d53a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.3+cbe9176f3a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a3a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		farsighted-mobs: Farsighted Mobs 1.0a
		fatxporbs: Fat Experience Orbs 0.0.9
		fermion: Fermion 2.1.191
		fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
		fiber: fiber 0.23.0-2
		flamingo_ooo: Flamingo, oh, oh, oh... 1.0.4-MC1.16.3-fabric
		flonters: Flonters 1.1.1+1.16.2
		frex: FREX 3.4.140
		gameinfo: GameInfo 1.5.4 1.16.4
		geckolib: Geckolib 2.0.0
		gentlefawn: GentleFawn 1.1.2-MC1.16.3-fabric
		givemehats: Give Me Hats! 1.4
		glassdoor: Glass Doors 1.5.0-1.16
		glassential: Glassential 1.16.4-1.1.5
		gobber2: Gobber2 2.3.38
		greater_eye: Greater Eye of Ender 1.1.4
		harvest_scythes: Harvest Scythes 1.0.6
		healthoverlay: Health Overlay 3.6.13
		hookshot: Hookshot 10.0
		horseinfo: Horse Info 0.2.2-1.16.1
		hotm: Heart of the Machine 1.16.3-0.1.7
		howlingwolves: Howling Wolves 1.0.0+build.1
		ignis-fatuus: Ignis Fatuus 1.1.0
		improved-stations: Improved Stations 2.0.3
		indrev: Industrial Revolution 1.7.15-BETA
		indypets: Independent Pets 0.2.0
		inmis: Inmis 1.3.1-1.16.2
		inventorysorter: Inventory Sorter 1.7.4-1.16
		jankson: Jankson 3.0.1+j1.2.0
		json-model-extensions: JSON Model Extensions 1.15.127
		jumpoverfences: JumpOverFences 1.16-0.0.3
		kibe: Kibe 1.6-BETA
		kirin: Kirin UI 1.7-1.16.2
		kubejs: KubeJS 1.5.5
		kykinite: Kykinite 1.1.4
		kyrptconfig: Kytpt Config 1.1.6-1.16
		lamps: The Lamps! 1.0
		lapisreserve: Lapis Reserve 1.0.6
		libblockattributes: LibBlockAttributes 0.8.4
		libblockattributes_core: LibBlockAttributes (Core) 0.8.5
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.5
		libblockattributes_items: LibBlockAttributes (Items) 0.8.4
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.2.2+1.16.3
		libstructure: LibStructure 1.5
		lightoverlay: Light Overlay 5.5.4
		lightstones: Lightstones 1.2
		llamasteeds: Llama Steeds 2020.2.8
		magna: Magna 1.4.3-1.16.2
		malilib: MaLiLib 0.10.0-dev.21+arne.2
		mcda: MC Dungeons Armors 0.8.5
		mcdw: MC Dungeons Weapons 2.3.5
		megane: megane 3.1.1+1.16.4
		megane-api: megane-api 3.1.1+1.16.4
		megane-impl: megane-impl 3.1.1+1.16.4
		megane-runtime: megane-runtime 3.1.1+1.16.4
		minecraft: Minecraft 1.16.4
		mm: Manningham Mills 2.1
		mo_glass: Mo Glass 1.5-MC1.16.4
		modern_industrialization: Modern Industrialization 0.3.9
		modid: Damage Tilt 1.16-fabric-0.1.0
		modmenu: Mod Menu 1.14.13+build.19
		moretotems: More Totems 2.7.1
		mostructures: Mo' Structures 1.0.1+mc.1.16.4
		mousewheelie: Mouse Wheelie 1.6.1+mc1.16.4
		musicdr: Music Duration Reducer 1.1.3
		mythicmetals: Mythic Metals 0.9.8
		no-potion-offset: No Potion Offset ${version}
		nookbuild: NookBuild 1.2.1
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_joml_joml: joml 1.9.25
		org_yaml_snakeyaml: snakeyaml 1.26
		packages: Packages 1.1.1
		parakeetmod: The Parakeet Mod 1.16.3-1.0.6
		patchouli: Patchouli 1.16.4-48-FABRIC
		piglib: Piglib 1.0.1
		plantusmaximus: Plantus Maximus 1.0.0-1.16.4
		playerabilitylib: Pal 1.2.1
		pling: Pling 1.3.0
		presencefootsteps: Presence Footsteps r29+1.16.4
		queks_end: Quek's End 1.1
		quickshulker: Quick Shulker 1.1.11-1.16
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		reborncore: Reborn Core 4.6.2+build.108
		repurposed_structures: Repurposed Structures 1.16.4-1.7.3
		roughlyenoughitems: Roughly Enough Items 5.8.10
		roughlyenoughitems-api: REI (API) 5.8.10
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.10
		roughlyenoughitems-runtime: REI (Runtime) 5.8.10
		sakurarosea: Sakura Rosea 1.6.0-MC1.16.3-fabric
		seasons: Fabric Seasons 1.0.3-BETA
		shapes: Shapes 2.0.0+build.10
		shulkerboxtooltip: Shulker Box Tooltip 2.3.3+1.16.4
		simpleteleporters: Simple Teleporters 2.2.0
		simplyplatinum: Simply Platinum 2.1
		slight-gui-modifications: 'Slight' GUI Modifications 1.6.1
		slotlock: SlotLock 1.0.1-BETA
		staffofbuilding: Staff of Building 1.2.4-1.16.2
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stopstridersuffering: Stop Strider Suffering 1.0.1-mc1.16.4-fabric
		strawdummy: Straw Dummy 1.4.0
		structure-helpers: Structure Helpers 3.0.0
		tacocraft: TacoCraft 1.3.1+mc.1.16
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 3.7.2+build.189
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.1
		terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.0.0+build.1
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.4
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
		terrestria: Terrestria 2.1.5+build.28
		the_bumblezone: The Bumblezone - Fabric 1.16.3-2.2.13
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		totemmod: Wither Totems Mod 0.3.2
		trapexpansion: Trap Expansion 1.3.2
		traverse: Traverse 3.2.0+build.17
		trinkets: Trinkets 2.6.7
		truerooms: True Secret Rooms 1.1.2-hotfix
		tweakeroo: Tweakeroo 0.10.0-dev.20201110.132827
		tweed: Tweed API 3.0.0-beta.22
		unearthed: Unearthed 1.0.5
		universalcomponents: Universal Components 0.7.3+1.16.2
		unsaddlepigs: Unsaddle Pigs 1.0.1-mc1.16.4-fabric
		upstream: Upstream 1.0.1
		vanilla-hammers: Vanilla Hammers 3.0.1-1.16.3
		vanilladeathchest: VanillaDeathChest 1.16.3-1.11.0.7-fabric
		vanillaexcavators: Vanilla Excavators 1.1.0
		villagerhats: Villager Hats fabric-1.16.4-1.0.1
		villagernames: Villager Names 1.6.0
		voyager: Voyager 1.0.0
		waila: Hwyla 1.9.22
		waystones: Waystones 1.0.10
		wild_explorer: Wild Explorer 1.3.1
		wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
		woodenhoppers: Wooden Hoppers 1.0.0
		woods_and_mires: Woods and Mires 1.0.4+1.16.3
		wrenchable: Wrenchable 1.0.0+1.16.1
		yosbr: YOSBR 0.1.0
		yungsapi: YUNG's API 1.16.4-Fabric-1
		zoob: Monster Of The Ocean Depths 2.5.0
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.10.8-1.16.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by LordDeatHunter** [comment]
Use the latest version of MythicMetals (0.9.9-snapshot or higher)
https://www.curseforge.com/minecraft/mc-mods/mythicmetals/files/3153510

**Comment by Rea2Die** [comment]
> Use the latest version of MythicMetals (0.9.9-snapshot or higher)
> https://www.curseforge.com/minecraft/mc-mods/mythicmetals/files/3153510

link not found

**Comment by LordDeatHunter** [comment]
The creator of MythicMetals has deleted the snapshot builds since he made official releases. Just use the latest version of MythicMetals and you're good to go.
