### ISSUE TITLE
No effect from Fortune 

### ISSUE THREAD

**Issue by Venaf** [LordDeatHunter/HarvestScythes#20]
Not sure if this is a bug or just a missing feature or design decision, but there's no effect from enchanting a scythe with fortune and then harvesting with Crop Reaper.  It does work when breaking the crop directly with the Fortune enchanted scythe. Is it possible to add/fix this?

**Comment by LordDeatHunter** [comment]
Fixed in v2.1.0+, should be up on CF in a short while.
