### ISSUE TITLE
Latest version not compatible with Aether

### ISSUE THREAD

**Issue by red2blue** [LordDeatHunter/HarvestScythes#21]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 11/11/21, 7:33 PM
Description: Initializing game

java.lang.NoClassDefFoundError: com/aether/items/utils/AetherTiers
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61)
	at wraith.harvest_scythes.support.AetherSupport.loadItems(AetherSupport.java:15)
	at wraith.harvest_scythes.HarvestScythes.load(HarvestScythes.java:112)
	at net.minecraft.client.MinecraftClient.handler$fjf000$inject(MinecraftClient:22548)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:457)
	at net.minecraft.client.main.Main.main(Main:179)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: com.aether.items.utils.AetherTiers
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 12 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at wraith.harvest_scythes.support.AetherSupport.loadItems(AetherSupport.java:15)
	at wraith.harvest_scythes.HarvestScythes.load(HarvestScythes.java:112)
	at net.minecraft.class_310.handler$fjf000$inject(class_310.java:22548)
	at net.minecraft.class_310.<init>(class_310.java:457)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 612368384 bytes (584 MiB) / 1811939328 bytes (1728 MiB) up to 7449083904 bytes (7104 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce RTX 2080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e87
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9649
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.47
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.47
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.47
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.47
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 36699.29
	Virtual memory used (MB): 27610.25
	Swap memory total (MB): 4000.00
	Swap memory used (MB): 557.20
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7104m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		addendum: Addendum 1.0.2
		adorn: Adorn 2.3.1+1.17.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		advancementplaques: Advancement Plaques 1.4.2
		advancements-enlarger: Advancements Enlarger 0.2.4
		adventurez: AdventureZ 1.4.2
		ae2wtlib: AE2WTLib 9.0.0-beta.8
		agape_space: Space Dimensions 0.3.5
		alloy_forgery: Alloy Forgery 2.0.6
		ambientenvironment: Ambient Environment 6.0.22
		apoli: Apoli 2.0.5
		appleskin: AppleSkin mc1.17.1-2.2.0
		appliedenergistics2: Applied Energistics 2 9.0.0-beta.2
		aqupdcaracal: Caracal mob 1.17-1.3.2
		arcanus: Arcanus 1.23
		architects_palette: Architect's Palette Fabric 1.3
		architectury: Architectury 2.6.35
		armorsoundtweak: Armor Sound Tweak 3.1.0
		artifality: Artifality 0.4.2
		artifice: Artifice 0.15.3+21w07a
		attributefix: Attribute Fix {FABRIC} 1.0.3
		audiooutput: AudioOutput 0.0.4
		authme: Auth Me 1.5.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		balm-fabric: Balm 1.3.0+0
		battletowers: Battle Towers 3.4.1-1.17.1
		bclib: BCLib 0.5.0
		bebooks: Better Enchanted Books 1.2.12
		bedrockwaters: BedrockWaters 1.5.0+1.17.1
		beenfo: Beenfo 1.17.1-fabric0.36.1-1.3.2
		better_wandering_trader: Better Wandering Trader 1.7.0
		betterdungeons: YUNG's Better Dungeons 1.17-1.0.2
		betterend: Better End 0.12.2
		betterf3: BetterF3 1.1.5
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		betternether: Better Nether 5.3.9
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.2
		bewitchment: Bewitchment 1.17-12
		bitsandchisels: BitsAndChisels 2.5.3
		blame: Blame 1.17-4.2.0-fabric
		blast: BLAST 1.8
		blockshifter: Blockshifter 1.4.0+fabric-1.17.1
		blockus: Blockus 2.2.10+1.17.1
		blue_endless_jankson: jankson 1.2.1
		blur: Blur (Fabric) 2.4.0
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.2-1.17.1
		bountiful: Bountiful 1.0.0
		breakprogress: Break Progress 1.0.1
		buildinggadgets: st'ructure tools 1.0.4
		calio: Calio 1.3.0
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.1.0
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		carpet: Carpet Mod 1.4.52
		carpet-extra: Carpet Extra 1.4.51
		carpet-tis-addition: Carpet TIS Addition 1.24.0+build.742
		carrier: Carrier 1.8.1
		chalk: Chalk 1.0.2
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		chat_heads: Chat Heads 0.5.0
		chesttracker: Chest Tracker 1.1.1
		cleancut: CleanCut 1.17-4.0-fabric
		cleardespawn: Clear Despawn 1.17.1-1.1.2
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config-lite: cloth-config-lite 2.0.6
		cloth-config2: Cloth Config v5 5.1.40
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		collective-fabric: Collective (Fabric) 1.62
		colorutility: ColorUtility 2.0.1
		com_electronwill_night-config_core: core 3.6.4
		com_electronwill_night-config_toml: toml 3.6.4
		com_flowpowered_flow-math: flow-math 1.0.3
		com_github_dimensionaldevelopment_poly2tri_java: poly2tri.java 0.1.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compactstatuseffects: Compact Status Effects 2.0.1
		companion_bats: Companion Bats 1.18.4
		completeconfig: CompleteConfig 1.0.0
		compress: Compress 'em [v1.5]
		conjuring: Conjuring 1.0.13
		consistency_plus: Consistency Plus 0.4.1+1.17
		continuity: Continuity 1.0.2+1.17
		cosmetic-armor: Cosmetic Armor 1.1.0
		cosmetica: Cosmetica 0.2.1
		craftingtweaks: Crafting Tweaks 13.0.0+0
		craftpresence: CraftPresence 1.8.8
		crookedcrooks: Crooked Crooks 2.0.0+1.17.1
		croparia: Croapria 1.17.1-0.0.4
		croptopia: Croptopia 1.6.3
		croptosis: Croptosis 1.1.3
		crowdin-translate: CrowdinTranslate 1.3+1.17
		cursormod: Custom Cursor Mod 1.3.0
		customportalapi: Custom Portal Api 0.0.1-beta46-1.17
		customportals: Custom Portals 2.1.0
		customstars: Custom Stars 0.7+1.17
		dark-enchanting: Dark Enchanting 0.4.1-1.17.1
		darkpaintings: Dark Paintings 4.0.2
		dataattributes: Data Attributes 1.0.6
		deathlog: DeathLog 0.2.2
		detailab: Detail Armor Bar 2.6.1+1.17.1-fabric
		dimdoors: DimensionalDoors 4.0.0+beta.3-27.10.2021
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dml-refabricated: Deep Mob Learning: Refabricated 0.4.4-beta
		dml-refabricated-base: DML: Refabricated - Base 0.4.4-beta
		dml-refabricated-events: DML: Refabricated - Vanilla Events 0.4.4-beta
		dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 0.4.4-beta
		dml-refabricated-rei: DML: Refabricated - REI Integration 0.4.4-beta
		dmlsimulacrum: Deep Mob Learning: Simulacrum 1.0.5
		doom: Doom Fabric 4.0.32
		dragonloot: DragonLoot 1.0.9
		drippyloadingscreen: Drippy Loading Screen 1.2.1
		dungeons_arise: When Dungeons Arise 2.1.48-fabric
		dynamicfps: Dynamic FPS 2.0.6
		eldritch_mobs: Eldritch Mobs 1.9.6
		emagnet: E Magnet 1.2.3
		enchant_giver: Enchant Giver 1.1.0
		enchantedbookredesign: Enchanted Book Redesign 1.17.1-2.0
		enchantmentdescriptions: Enchantment Descriptions 4.0.1
		enhancedcelestials: Enhanced Celestials 2.0.5
		entityculling: EntityCulling-Fabric 1.3.3
		equipmentcompare: Equipment Compare 1.2.7
		expandedstorage: Expanded Storage 7.2.7
		extraalchemy: Extra Alchemy 1.6.1
		extragenerators: Extra Generators 1.1-BETA+1.17
		extraorigins: Extra Origins 1.17-10
		fabric: Fabric API 0.42.1+1.17
		fabric-api-base: Fabric API Base 0.4.0+5847535018
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+5847535018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+5847535018
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+5847535018
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+5847535018
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+5847535018
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+5847535018
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.1+5847535018
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+5847535018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.13+5847535018
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.1+5847535018
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.11+5847535018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+5847535018
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+5847535018
		fabric-item-api-v1: Fabric Item API (v1) 1.2.5+5847535018
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+5847535018
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+5847535018
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.3+5847535018
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.5+5847535018
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+5847535018
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.2+6d0fac4218
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.5+6d0fac4218
		fabric-models-v0: Fabric Models (v0) 0.3.1+5847535018
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+5847535018
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+5847535018
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+5847535018
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.11+6d0fac4218
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.5+6d0fac4218
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+5847535018
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+5847535018
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+5847535018
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.9+5847535018
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+6d0fac4218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+5847535018
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+6d0fac4218
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+6d0fac4218
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+6d0fac4218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.9+5847535018
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+5847535018
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+5847535018
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.14+5847535018
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.2+5847535018
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+5847535018
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.1+eb76084f18
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.1+6d0fac4218
		fabricenchantments: Fabric Enchantments 0.5.0
		fabricloader: Fabric Loader 0.12.0
		fabrictailor: Fabric Tailor 1.7.1
		factory: Factory 1.17.1-1.4.0
		fake-player-api: Fake Player API 0.2.0
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fallingleaves: Falling Leaves 1.7.4+1.17.1
		fallingtree: FallingTree 2.14.3
		fancymenu: FancyMenu 2.3.5
		farmersdelight: Farmer's Delight 1.17.1-0.1.2
		fastfurnace: FastFurnace 1.17-3.0
		fatxporbs: Fat Experience Orbs 1.0.1
		fermion: Fermion 2.11.241
		fermion-modkeys: Fermion Modifier Keys 1.10.241
		ferritecore: FerriteCore 3.1.0
		fiber: fiber 0.23.0-2
		flytre-lib-base: Flytre Lib - Base Module 1.3.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.2
		flytre_lib: Flytre Lib 1.4.2
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.21
		givemehats: Give Me Hats! 1.6.5
		glassdoor: Glass Doors 1.5.0-1.16
		glassential: Glassential 1.17-1.2.0
		go-fish: Go Fish 1.3.0-beta-1.17.1
		goat: Goat origin 1.0.0
		gobber2: Gobber2 2.4.58
		goldenhoppers: Golden Hoppers 1.1.0
		golemsgalore: Golems Galore 1.0.3-1.17.1
		guifollowers-fabric: GUI Followers (Fabric) 1.7
		harvest_scythes: Harvest Scythes 2.1.0
		hctm-base: HCTM Base 3.6.2
		healthoverlay: Health Overlay 4.0.2
		heartbond: Heartbond 1.1.0
		hologram-api: Hologram API 0.2.1+1.17.1
		hookshot: Hookshot 22.0
		horseinfo: Horse Info 0.3.0-1.17
		horsestonks: Horse Stonks 1.0.0
		hydrogen: Hydrogen 0.3
		iceberg: Iceberg 1.0.23
		iknowwhatimdoing: I Know What I'm Doing 3.1.0
		impersonate: Impersonate 2.3.5
		improved-stations: Improved Stations 2.0.7
		incantationem: Incantationem 1.1.2+1.17.1
		incubus_core: Incubus Core 1.6.1
		indium: Indium 1.0.0+mc1.17.1
		indrev: Industrial Revolution 1.12.0-BETA
		inmis: Inmis 2.3.2-1.17.1
		inventoryprofilesnext: Inventory Profiles Next 1.1.3
		iris: Iris 1.1.2+build.9
		ironfurnaces: Iron Furnaces 1.17.1-2.7.1-fabric
		itemborders: Item Borders 1.1.3
		itemscroller: Item Scroller 0.15.0-dev.20210707.005506
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		jumpoverfences: JumpOverFences 1.16-0.0.3
		justenoughkeys: Just Enough Keys 0.3.2
		kambrik: Kambrik 1.1.0
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kibe: Kibe 1.9.3-BETA+1.17
		kirin: Kirin UI 1.9.1
		kjsextras: KubeJS Extras 1.4.0
		konkrete: Konkrete 1.3.0
		ktdatataglib: KtDataTagLib 1.5.4
		kubejs: KubeJS 1701.3.10-build.9999
		kyrptconfig: Kyrpt Config 1.2.1-1.17
		lacrimis: Lacrimis 2.1.3+1.17.1
		lambdabettergrass: LambdaBetterGrass 1.2.1+1.17
		lambdynlights: LambDynamicLights 2.0.2+1.17
		lazydfu: LazyDFU 0.1.2
		legendarytooltips: Legendary Tooltips 1.1.2
		libaddict: libaddict 0.3.0
		libblockattributes: LibBlockAttributes 0.9.2
		libblockattributes_core: LibBlockAttributes (Core) 0.9.2
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.2
		libblockattributes_items: LibBlockAttributes (Items) 0.9.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.2.1+1.17.1
		libninepatch: LibNinePatch 1.1.0
		libra: Libra 0.4.0.1
		lightestlamp: Lightest Lamps 0.9.6
		lightoverlay: Light Overlay 6.0.1
		lithium: Lithium 0.7.5
		logical_zoom: Logical Zoom 0.0.11
		lovely_snails: Lovely Snails 1.0.3+1.17
		lumiwool: Luminous Wool 1.2.0
		maelstrom_library: Maelstrom Library 1.2.2-1.17.1
		magicfungi: Magic Fungi 0.5.0-BETA+1.17.1
		magna: Magna 0.4.0-1.17.1
		malilib: MaLiLib 0.10.0-dev.26
		matrix: Matrix 1.0.0
		maybe-data: Maybe data 1.0.1-1.17
		mcda: MC Dungeons Armors 1.7.15
		mcdar: MC Dungeons Artifacts 1.4.2
		mcdict: MCDict 2.1.0+1.17.1
		mcdw: MC Dungeons Weapons 3.6.0
		mcsa: MC Story Mode Armor 2.3.2-1.17
		mealapi: Meal API 0.3+1.17
		megane: megane 5.5.1
		megane-applied-energistics-2: megane-applied-energistics-2 5.5.1+9.0.0-beta.1
		megane-base: megane-base 5.5.1
		megane-dml-simulacrum: megane-dml-simulacrum 5.5.1+1.0.5
		megane-extra-generators: megane-extra-generators 5.5.1+1.1-BETA-1.17
		megane-fabric-transfer: megane-fabric-transfer 5.5.1+1.5.1-6d0fac4218
		megane-industrial-revolution: megane-industrial-revolution 5.5.1+1.11.0-alpha.4
		megane-kibe: megane-kibe 5.5.1+1.9.3-BETA-1.17
		megane-lib-block-attributes: megane-lib-block-attributes 5.5.1+0.9.0
		megane-reborn-core: megane-reborn-core 5.5.1+5.0.11-beta
		megane-runtime: megane-runtime 5.5.1
		megane-team-reborn-energy: megane-team-reborn-energy 5.5.1+2.0.0-beta1
		megane-tech-reborn: megane-tech-reborn 5.5.1+5.0.11-beta
		megane-vanilla: megane-vanilla 5.5.1+1.17.1
		megane-wireless-networks: megane-wireless-networks 5.5.1+1.3.1
		midnightlib: MidnightLib 0.3.0
		minecraft: Minecraft 1.17.1
		minecraftcapes: MinecraftCapes Mod 11.0.1
		minershorizon: Miner's Horizon 1.7.2-1.17.1
		mm: Manningham Mills 2.3
		mo_glass: Mo Glass 1.5-MC1.17.1
		mocolors: Mo' Colors 1.2.2
		modmenu: Mod Menu 2.0.14
		morebannerfeatures: More Banner Features 1.0.9
		moretags: More Tags 1.2.5
		morevillagers-fabric: MoreVillagersFabric 2.1.1-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		multipart_entities: MultipartEntities 1.1.3-1.17.1
		myron: Myron 1.6.1
		mythic-mounts: Mythic Mounts 1.17.1-2.0
		mythicmetals: Mythic Metals 0.10.1
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.2.4
		noanglebrackets: NoAngleBrackets 1.1.0
		nomoreglowingpots: No More Glowing Pots 1.0.2
		notenoughcrashes: Not Enough Crashes 4.0.0+1.17.1
		notes: Notes 1.0.8
		nyfsquivers: Nyf's Quivers Fabric-0.2.6
		omega-config: OmegaConfig 1.0.8
		openloader: OpenLoader 3.0.1
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		org_jgrapht_jgrapht-core: jgrapht-core 1.1.0
		org_objenesis_objenesis: objenesis 3.2
		org_yaml_snakeyaml: snakeyaml 1.29
		origins: Origins 1.1.4
		origins-classes: Origins: Classes 1.2.2
		owo: oωo 0.3.0
		packet_tweaker: Packet Tweaker 0.2.0+1.17.1
		patchouli: Patchouli 1.17.1-56-FABRIC
		pehkui: Pehkui 2.5.3+1.14.4-1.18
		phonos: Phonos 0.1.2+1.17
		pipe: Pipe 1.6.0
		placeholder-api: Placeholder API 1.1.1+1.17.1
		plantinajar: Plant In A Jar 2.2.2
		playerabilitylib: Pal 1.3.0
		pling: Pling 1.4.0
		polymer: Polymer 0.1.8+1.17.1
		polymorph: Polymorph 0.0.14-1.17.1
		prefab: Prefab 2.1.6
		presencefootsteps: Presence Footsteps r32-1.17-rc1
		pugh_lib: Pugh Lib ${version}
		pugh_tools: Pugh Tools ${version}
		qcommon-cfg-core: qcommon-cfg-core 3.3.0
		qcommon-croco: Croco 2.1.1
		quarrymod: Industial Quarry Mod 0.5.2
		quickshulker: Quick Shulker 1.3.1-1.17
		ratsmischief: Rat's Mischief 1.3.1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.0.11-beta
		redbits: Red Bits 1.10.1
		reeses-sodium-options: Reese's Sodium Options 1.2.0
		repurposed_structures: Repurposed Structures 2.5.5+1.17.1
		reroll: Reroll 1.3.0-1.17.1
		resourceful_tools: Resourceful Tools 1.1.22
		respawnablepets: Respawnable Pets 1.17-5
		rhino: Rhino 1701.1.5-build.71
		right-click-clear: Right Click Clear 2.0.3
		roughlyenoughitems: Roughly Enough Items 6.1.329
		rpgstats: RPGStats 4.2.2+1.17.1
		rswires: RSWires 4.11.2
		sandwichable: Sandwichable 1.2-rc2+1.17
		satin: Satin 1.6.4
		schmucks: Schmucks 1.4.0
		secretrooms: Secret Rooms 1.1.0+1.17
		seedy-behavior: Seedy Behavior 1.0.2+1.17.1
		server_translations_api: Server Translations API 1.4.6+1.17
		sgui: SGui 1.0.0-rc4+1.17.1
		shulkerboxtooltip: Shulker Box Tooltip 3.0.3+1.17.1
		shulkerutils: shulkerutils 1.0.4-1.17
		skinlayers: 3d Skin Layers 1.2.1
		skyvillages: Sky Villages 1.0.0-fabric
		sodium: Sodium 0.3.2+IRIS2-build.9
		sodium-extra: Sodium Extra 0.3.5
		somnus: Somnus API 0.0.14-1.17.1
		soulbound: Soulbound 2.0.0
		spruceui: SpruceUI 3.3.0+1.17
		stacc: Stacc 1.2.3
		staffofbuilding: Staff of Building 1.3.2-1.17
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter_recipe_tags: Stonecutter Recipe Tags 1.1.0
		storagecabinet: Storage Cabinet 1.4.1
		strawdummy: Straw Dummy 1.5.0
		structure-helpers: Structure Helpers 3.2.0
		structurized: Structurized 1.3.0
		team_reborn_energy: Energy 2.0.0-beta1
		techreborn: Tech Reborn 5.0.11-beta
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terralith: Terralith for Fabric 1.6.1
		the_aether: The Aether Reborn 1.17.1-1.6.0
		things: Things 0.2.6
		toms_storage: Tom's Simple Storage Mod 1.1.18
		toolstats: Tool Stats 2.0.1
		tooltipfix: ToolTip Fix 1.0.4-1.17.1
		torohealth: ToroHealth Damage Indicators 1.17.1-fabric-12
		transportables: Transportables 1.0.6
		trinkets: Trinkets 3.0.4
		truerooms: True Secret Rooms 1.1.5
		universal-graves: Universal Graves 1.1.3+1.17.1
		untitledduckmod: Untitled Duck Mod 0.3.0
		upgradedshulkers: Upgraded Shulkers 1.1.1-1.17
		urns: Urns 1.0.1
		valley: ValleyCraft 1.3.2
		veinmining: Vein Mining 0.0.11-1.17.1
		villager-hats: Villager Hats Mod 1.2.1
		villagernames: Villager Names 2.0.1
		visuality: Visuality 0.3.0
		voidtotem: Void Totem (Fabric) 1.17.0-1.0.0
		voidz: VoidZ 1.0.5
		ward_blocks: Ward Blocks 1.1.9
		waterdripsound: Drip Sounds 1.17-0.2.2
		waystones: Waystones 2.2.0
		whereisit: Where Is It 1.14.3
		winged: Winged Mod 1.17.1-3.0.0
		wirelessnetworks: Wireless Networks 1.3.1
		wrenchable: Wrenchable 1.1.0+1.17
		wthit: wthit 3.11.1
		xaerominimap: Xaero's Minimap 21.21.0
		xaeroworldmap: Xaero's World Map 1.18.1
		xlpackets: XLPackets 2.0-1.17
		xps: Xp Obelisk 0.2.2.r_for_1.17.x_Fabric
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.17-Fabric-19
		zihlaunchpads: ZIHLaunchpads 1.1.1
	Launched Version: fabric-loader-0.12.0-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
	Suspected Mods: Fabric Loader (fabricloader), Balm (balm-fabric)

**Comment by LordDeatHunter** [comment]
Where did you get that version (1.6.0)? The latest version I could find on CF was 1.5.0, which is what I made the compat for.

**Comment by red2blue** [comment]
it's their latest from github. they plan to release it this month.

**Comment by Jack-Papel** [comment]
1.6.0 is now on CF

**Comment by serioos** [comment]
I have the same issue. I reported it to Aether modders and I'll put the link here too.

https://github.com/devs-immortal/Paradise-Lost/issues/553

**Comment by LordDeatHunter** [comment]
Should be fixed in 2.1.1
