### ISSUE TITLE
Executable bit is set on config.json

### ISSUE THREAD

**Issue by Calendis** [LordDeatHunter/HarvestScythes#25]
`Harvest Scythes 2.4.0`

For owner, permissions are set to rwx, instead of just rw.

Since this is just a text file, this shouldn't be the case. This doesn't really cause any issues, and I just unset it so not a big deal but still...

**Comment by LordDeatHunter** [comment]
Yikes, the config code is recycled from some of my other projects, and I can see how that could be an issue. Nice find.
