### ISSUE TITLE
[1.18.1] Crash after placing an Anvil 

### ISSUE THREAD

**Issue by pewblaze** [LordDeatHunter/HarvestScythes#29]
It crashes when im placing an anvil.

[crash-2021-12-13_00.19.19-client.txt](https://github.com/LordDeatHunter/HarvestScythes/files/7954520/crash-2021-12-13_00.19.19-client.txt)

[latest.log](https://github.com/LordDeatHunter/HarvestScythes/files/7954521/latest.log)

**Comment by pewblaze** [comment]
Nevermind ^^"

**Comment by LordDeatHunter** [comment]
What was the issue? Outdated version?
