### ISSUE TITLE
No mention on curseforge that this is fabric and not forge mod

### ISSUE THREAD

**Issue by AmyMoriyama** [LordDeatHunter/HarvestScythes#46]
Just spent a good fifteen minutes trying to figure out why the mod didn't load. Then I realized after looking on github that this is a fabric mod. I really wish fabric never existed. It has caused so much trouble and confusion.

**Comment by Hydroquake** [comment]
Whenever you download a mod, it shows what loader it is for. You should check to see what modloader a mod is before downloading it.

**Comment by LordDeatHunter** [comment]
It literally does tho, what are you on about?
![image](https://github.com/LordDeatHunter/HarvestScythes/assets/26803198/e93502c8-f993-4d34-b864-93cedd21c749)
