### ISSUE TITLE
Missing Tag on modrinth

### ISSUE THREAD

**Issue by SylisMC** [LordDeatHunter/HarvestScythes#50]
Harvest Scythes 2.5.6 - MC1.20 i missing the 1.20.1 tag on [modrinth](https://modrinth.com/mod/harvest-scythes/version/2.5.6+MC1.20), so you cant find it (easily) on the Modrinth app. Mod wont show up on 1.20.1+ unless you override the version in the managers search parameters
![image](https://github.com/LordDeatHunter/HarvestScythes/assets/19602662/ee05d85a-626c-4198-b7c3-8ce2e78c2cd3)
![image](https://github.com/LordDeatHunter/HarvestScythes/assets/19602662/d7056905-5ff2-40b0-8c3c-6c7c9f7d1329)

**Comment by LordDeatHunter** [comment]
Updated
