### ISSUE TITLE
Constant crashing with this mod installed

### ISSUE THREAD

**Issue by Sunconure11** [LordDeatHunter/HarvestScythes#6]
https://pastebin.com/EdP1mDX6

**Comment by Sunconure11** [comment]
On an unrelated note, would it be possible to add support for Terran Expansion?

**Comment by LordDeatHunter** [comment]
Update MythicMetals. It's stated on the CurseForge page to use v0.9.9 or newer.

**Comment by LordDeatHunter** [comment]
As for TerranExpansion, I'll keep it in mind for a later date. I am currently taking a bit of a break from modding.

**Comment by Sunconure11** [comment]
I went and tried the build against the newer version of Mythic Metals, and I am now getting not the exact same error, but something very similar.

https://pastebin.com/fmSgfWCh

**Comment by Sunconure11** [comment]
Something in More Gems changed.
