### ISSUE TITLE
Referring to a previous issue, as I am having it as well

### ISSUE THREAD

**Issue by CannibalKon** [LordDeatHunter/HarvestScythes#8]
#4 
I realized, with this mod installed, if you go over a certain limit of active mods, the crash listed there will happen.
I tested it with and without Harvest Scythes, and without it, I will not crash no matter how many mods I have installed, but with it installed, it will output that crash after a certain number.

I tested by switching between mods, swapping one out for another, and they never crashed, but the moment I went over a certain limit (I didn't count specifically), I would crash just like that.

I'm unsure what this means, or how to fix it, but I did want to clarify that this issue does exist with this mod installed, and only this one.
So it's not an error between mods, but seems to be an error after having a certain amount.

**Comment by LordDeatHunter** [comment]
Can you post a crash log?
https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes
Having NotEnoughCrashes installed as well would help a lot.

**Comment by CannibalKon** [comment]
Okay, so I had done a bit of tinkering after I disabled this mod, so the list will look a little different, but what I did was just pop on both NEC and HS to generate this crash:
https://pastebin.com/4fUzNEzH
Which happens before being able to initialize the game.

I will also attach a pastebin of the crash before I disabled the mod (without NEC):
https://pastebin.com/QD1W1m4A

had to remove some irrelevant footstep errors to fit that log in a pastebin, but wanted both for continuity's sake.
Hope this helps!

**Comment by Intezium** [comment]
I finded active mods limit, it's 384 mods. More than 384 - crash.

**Comment by LordDeatHunter** [comment]
Can any of you join my discord and help me debug?
https://discord.gg/vMjzgS4

**Comment by LordDeatHunter** [comment]
Should be fixed as of 2.0.1
