### ISSUE TITLE
More Gems Crash

### ISSUE THREAD

**Issue by Intezium** [LordDeatHunter/HarvestScythes#9]
Minecraft 1.16.5
Fabric Loader 0.11.3
Fabric API 0.32.0
More Gems 1.1.22
Harvest Scythes 1.0.9

[crash-2021-03-20_16.26.03-client.txt](https://github.com/LordDeatHunter/HarvestScythes/files/6175645/crash-2021-03-20_16.26.03-client.txt)

**Comment by kwpugh** [comment]
Howdy.  The user opened an issue with me as well on this.   I re-wrote my tool material list from a a single enum class into separate classes to allow for greater customization via config.   You will likely need to adjust accordingly.
